### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by knkrth** [carsenk/denariiumx-server#1]
How to find `P2PKH_VERBYTE` `P2SH_VERBYTES`  `WIF_BYTE` from the public & private key?

**Comment by metaspartan** [comment]
They are the hex values for Denarius addresses, private keys, and wallet import format, etc.

Denarius uses 30 (Hex is 1E) for the P2PKH_VERBYTE and Bitcoin uses 0, which the hex is also 0.

The WIF_BYTE, which is 128 + the P2PKH_VERBYTE. Denarius uses 158 (Hex is 9E).

The P2SH_VERBYTES is 90 (Hex 5A)

**Comment by knkrth** [comment]
How do you find P2SH_VERBYTES is 90?

**Comment by metaspartan** [comment]
It is the SCRIPT_ADDRESS, https://github.com/carsenk/denarius/blob/master/src/base58.h#L281

Which is a Base58 Prefix Decimal which equals out to 'd'

**Comment by knkrth** [comment]
Thank you :+1:
